### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by diegobernardes** [victorspringer/http-cache#1]
Hi @victorspringer, this is my code review about this project.

Make sure it is compliant with [RFC7234](https://datatracker.ietf.org/doc/rfc7234/). Another good resource about http caching is the Mozilla [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers).

You shouldn't commit the `vendor` folder as you acting as a library and not a application. Keep `Gopkg.toml` for ci and tests, so everytime you run a `dep ensure` the tests gonna be deterministic as they run against the same expected dependencies.

Don't really like the `Config` structure, initialize the values at the `Client` and then check if it has everything you need. But this is personal taste.
https://github.com/victorspringer/http-cache/blob/f66d06016cc24d1c99972e789f5122b486683a75/cache.go#L58

This function has some fixed rules, it may be ok, but you could accept as params a new function on parameters to change the behaviour. What if the user want to cache `post`? What if only 2XX should be cached? 
https://github.com/victorspringer/http-cache/blob/f66d06016cc24d1c99972e789f5122b486683a75/cache.go#L91

This is my 2 cents.

**Comment by victorspringer** [comment]
Hi @diegobernardes,

I've already ignored `vendor` and changed `Client`/`Adapter` constructors. The remaining topics are in the roadmap. Thanks for the feedback!
