### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by andre-meneses-fivestars** [victorspringer/http-cache#16]
Hey @victorspringer, if you can help with these two questions, I'd appreciate.

- This uses "normal" memory, and does not expect a memcached instance installed, right?

- Would this be a good configuration for a Gorilla Mux router?

```
// Initialize the router
router := mux.NewRouter().StrictSlash(true)

//Memory Cache code
memcached, err := memory.NewAdapter(
  memory.AdapterWithAlgorithm(memory.LRU),
  memory.AdapterWithCapacity(10000000),
)
if err != nil {
  fmt.Println(err)
  os.Exit(1)
}

cacheClient, err := cache.NewClient(
  cache.ClientWithAdapter(memcached),
  cache.ClientWithTTL(30*time.Second),
  cache.ClientWithRefreshKey("opn"),
)
if err != nil {
  fmt.Println(err)
  os.Exit(1)
}
router.Use(cacheClient.Middleware)
```

Thank you!

**Comment by victorspringer** [comment]
Hi André,
yes, the `memory` package uses in-memory storage. The configuration looks good 👍

**Comment by meneses-pt** [comment]
Thank you for your response @victorspringer.
I'm using this on a live project: https://goals.zone/
The Backend project can be found on: https://github.com/meneses-pt/go_als.zone

Great work here
