### ISSUE TITLE
custom response writer seems to be messing with compression

### ISSUE THREAD

**Issue by floren** [victorspringer/http-cache#22]
Apologies for not providing a test, as I'm short on time, but I wanted to report that I believe 31fef4b80094b1df6adbc9161d5f2ea6c5b4e2f3 introduced issues with compression. Specifically, I'm seeing responses coming out of the cache with the headers indicating gzip compression, but the body is uncompressed.

**Comment by victorspringer** [comment]
Thanks for reporting @floren , that makes sense. I'll push a fix very soon.

**Comment by victorspringer** [comment]
Hi @floren how are you doing the compression? Through some other middleware?
If so, make sure to add this middleware **before** the cache middleware in the middleware chain.
