### ISSUE TITLE
Pute golang storage

### ISSUE THREAD

**Issue by gedw99** [victorspringer/http-cache#3]
Badger would be an excellent storage adapter.
Pure golang.
Fast and designed for SSD drives.

---

I would also like to make this work as a grpc middleware. That would be really useful because it would work for both grpc and http thanks to the grocery gateway and other similar libraries.

The other thing is the caching logic in relation to the storage. You normally want intimate control of this and I noticed you had some really good generic algo . But often you want to be able to pin certain namespaces.
For example anything that was related to authourisation data you would want pinned into the cache because you always want it.
This together with warmup of an empty cache would mean your most important data is always there.

Just my 2 cents...

As far as coding styles the other issue before me commented a fair bit

**Comment by victorspringer** [comment]
Hi @gedw99,

Thank you for the awesome suggestions, I've put everything in the roadmap!
